import Vue from "vue";
import { library } from "@fortawesome/fontawesome-svg-core";
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";
import {
  faUser,
  faSmile,
  faPaperclip,
  faPaperPlane,
  faEnvelopeOpenText,
  faUserFriends,
  faCog,
  faEraser,
  faMarker,
  faTint,
  faCheckCircle,
  faCheck,
  faHeartBroken,
  faLockOpen,
  faComment,
  faCommentAlt,
  faEnvelope,
  faSearch,
  faKeyboard,
  faSortAmountUpAlt,
  faTrash,
  faSignOutAlt,
  faAngleLeft,
  faTimes,
  faCamera,
  faCaretDown,
  faAngleDown,
  faHeart,
  faCommentSlash,
  faBan
} from "@fortawesome/free-solid-svg-icons";
library.add({
  faUser,
  faSmile,
  faPaperclip,
  faPaperPlane,
  faEnvelopeOpenText,
  faUserFriends,
  faMarker,
  faCog,
  faCamera,
  faEraser,
  faTint,
  faCheckCircle,
  faHeartBroken,
  faCheck,
  faLockOpen,
  faComment,
  faCommentAlt,
  faEnvelope,
  faKeyboard,
  faSearch,
  faSortAmountUpAlt,
  faTrash,
  faSignOutAlt,
  faAngleLeft,
  faTimes,
  faCaretDown,
  faAngleDown,
  faHeart,
  faCommentSlash,
  faBan
});
Vue.component("fa-icon", FontAwesomeIcon);
